---
sidebar: sidebar 
permalink: task-manage-private-aws.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, aws 
summary: Verwalten Sie Ihren allgemeinen und Hyperscaler-spezifischen, durchgängigen Private Offer Process und die Akzeptanz- und Aktivierungsleitfäden für NetApp Intelligent Services für AWS, Azure und Google Cloud. 
---
= Akzeptieren und konfigurieren Sie ein privates AWS Marketplace-Angebot für die NetApp Konsole
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Akzeptieren Sie ein privates Marketplace-Angebot für die NetApp Konsole in der AWS-Konsole und konfigurieren Sie die AWS-Anmeldeinformationen in der Konsole.

.Bevor Sie beginnen
* Arbeiten Sie mit dem NetApp -Vertrieb zusammen, um ein privates Angebot zu erstellen und den Aktivierungslink zu erhalten.
* Stellen Sie sicher, dass Sie über die erforderlichen AWS Marketplace-Berechtigungen verfügen:
+
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-private-offers-subscribing.html["Anzeigen und Abonnieren eines privaten Angebots"]
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-iam-users-groups-policies.html["Validierung der Käuferberechtigungen"]






== Akzeptieren Sie das private Angebot in der AWS-Konsole

Um den Kauf zu aktivieren und den ermäßigten Preis anzuwenden, muss die Abonnementzuweisung in der Konsole abgeschlossen werden.

[NOTE]
====
Sie müssen alle Schritte abschließen, um Ihr privates Angebot zu aktivieren. Das Überspringen von Schritten kann zu Abrechnungsfehlern führen. Bei mehrmaliger Annahme und Aktivierung des Angebots kommt es zu einer doppelten Abrechnung.

====
.Schritte
. Klicken Sie auf den Aktivierungslink für das private Angebot Ihres NetApp -Vertriebsteams. Der Link sollte ungefähr wie folgt aussehen:
`https://aws.amazon.com/marketplace/saas/ordering?productId=aaa&offerId=offer-aaa`
+
 If you did not receive the link, view private offers in the AWS Marketplace console. The following permissions are required:
+
** Verwenden von AWS-verwalteten Richtlinien: *AWSMarketplaceRead-only*, *AWSMarketplaceManageSubscriptions* oder *AWSMarketplaceFullAccess*
** Verwenden benutzerdefinierter IAM-Richtlinien: `aws-marketplace:ListPrivateListings` Und `aws-marketplace:ViewSubscriptions`


. Sie werden zum AWS Marketplace weitergeleitet, um das private Angebot anzuzeigen.
+
[NOTE]
====
Private Angebote werden zusätzlich zu öffentlichen Angeboten erstellt. Verwenden Sie das Dropdown-Menü *Angebotsauswahl*, um zwischen öffentlichen und privaten Angeboten zu wechseln.

====
. Überprüfen Sie die Details des privaten Angebots und bestätigen Sie, dass sie mit Ihrer Vereinbarung übereinstimmen. Wenn sie falsch sind, akzeptieren Sie sie nicht. Wenden Sie sich an Ihr NetApp -Account-Team.
+
[NOTE]
====
Es gibt zwei Arten von privaten Angeboten:

** *On-Demand-Nutzung*
+
*** Preisinformationen
*** Rechtliche Hinweise


** *Vertrag*
+
*** Dauer und Termine
*** Erneuerungseinstellungen
*** Vertragsoptionen
*** Gesamtvertragspreis




Bei Vertragsangeboten geben Sie bitte die vereinbarte Stückzahl an. Stellen Sie bei Cloud Volumes ONTAP sicher, dass Sie vor dem Abonnieren die richtige Lizenz auswählen.

====
. Um das private Angebot anzunehmen, gehen Sie wie folgt vor:
+
.. Klicken Sie für die On-Demand-Nutzung auf *Abonnieren*.
.. Bei Vertragsangeboten geben Sie die Stückzahl der einzelnen Leistungen ein und klicken auf *Vertrag erstellen*.


. Nach der Annahme bestätigt ein Banner das Abonnement und enthält Anweisungen zur Registrierung.
. Klicken Sie auf *Konto einrichten*. Dadurch wird eine Weiterleitung zur NetApp Konsole zur Konfiguration des Abonnements durchgeführt.
+
[NOTE]
====
Wenn Sie das Angebot angenommen, die Registrierung jedoch nicht abgeschlossen haben, kehren Sie zur Produktseite zurück. Klicken Sie bei Vertragslisten auf *Kaufoptionen anzeigen*, um das Angebot anzuzeigen, und wählen Sie dann *Konto einrichten*.

====
. Sign in bei https://console.netapp.com[] mit Ihrem Konsolenkonto.
. Navigieren Sie nach der Anmeldung zu https://console.netapp.com/licenses/overview[] . Sie werden aufgefordert:
+
.. Geben Sie einen *Anzeigenamen* für das Marketplace-Abonnement ein.
.. Wählen Sie die Konsolen-*Konten* mit Zugriff auf das Abonnement aus.
.. [Optional] Aktivieren Sie *Vorhandenes Abonnement ersetzen*, um ein vorhandenes Abonnement für ein Konto zu überschreiben.
+
[NOTE]
====
*** Der Ersatz gilt nur für ein Konsolenkonto.
*** Um mehrere Konten mit demselben Abonnement zu verknüpfen, konfigurieren Sie zusätzliche Konten manuell.
*** Wenn Anmeldeinformationen nie mit einem Abonnement verknüpft wurden, verknüpfen Sie sie manuell, wie im nächsten Abschnitt beschrieben.


====


. Klicken Sie auf *Zuordnen* und dann auf *Fertig*.


[IMPORTANT]
====
Um den ermäßigten Preis anzuwenden, ist es notwendig, die Abonnementzuweisung in der Konsole abzuschließen.

====


== Konfigurieren des Abonnements mit AWS-Anmeldeinformationen

. Gehen Sie in der Konsole zu *Governance > Lizenzen und Abonnements* und wählen Sie die Registerkarte *Marketplace-Abonnements* aus.
. Suchen Sie das zuvor erstellte Abonnement. Erweitern Sie die Zeile, um zu bestätigen, dass sie mit Ihrem Konsolenkonto verknüpft ist.
+
[NOTE]
====
Aufgrund von Einschränkungen des AWS Marketplace werden einige Details privater Angebote nicht außerhalb der AWS-Konsole angezeigt. Wenn ein Feld angezeigt wird `N/A` , überprüfen Sie die Informationen direkt in der AWS-Konsole.

====
. Klicken Sie auf das Drei-Punkte-Menü neben dem Abonnement und wählen Sie *Konfigurieren*.
. Wählen Sie die entsprechenden *AWS-Kontoanmeldeinformationen* aus und klicken Sie auf *Konfigurieren*.


[NOTE]
====
Die Marketplace-Gebühren für diese Anmeldeinformationen werden über das Marketplace-Abonnement abgerechnet. Bei Jahresverträgen werden die Kosten auf die Vertragsnutzung angerechnet.

====
[IMPORTANT]
====
Wiederholen Sie die Schritte 1–4 für jede AWS-Anmeldeinformation in Ihrem Konsolenkonto, die Sie mit dem Abonnement verknüpfen möchten.

* Für Anmeldeinformationen in anderen Konsolenorganisationen verwenden Sie das Dropdown-Menü *Organisation* und wiederholen Sie die Schritte.
* Für Anmeldeinformationen in anderen Agenten verwenden Sie das Dropdown-Menü *Agent* und wiederholen Sie die Schritte.


====