---
sidebar: sidebar 
permalink: task-manage-private-google-cloud.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, google cloud 
summary: Verwalten Sie Ihren allgemeinen und Hyperscaler-spezifischen, durchgängigen Private Offer Process und die Akzeptanz- und Aktivierungsleitfäden für NetApp Intelligent Services für AWS, Azure und Google Cloud. 
---
= Akzeptieren und konfigurieren Sie ein privates Google Cloud-Angebot für die NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 


[role="lead"]
Akzeptieren Sie ein privates Marketplace-Angebot für die NetApp Console in der Google Cloud-Konsole.  Konfigurieren Sie die Google Cloud-Anmeldeinformationen in der Konsole.

.Bevor Sie beginnen
* Arbeiten Sie mit dem NetApp -Vertrieb zusammen, um ein privates Angebot zu erstellen. Den Angebotslink muss Ihnen Ihr Vertriebsteam zur Verfügung stellen.
* Für Ihr Abrechnungskonto darf es sich nicht um eine kostenlose Testversion handeln. Kostenlose Testkonten können keine privaten Angebote annehmen. Wenn Sie versuchen, ein Testabrechnungskonto zu verwenden, erhalten Sie eine Fehlermeldung und benötigen Unterstützung vom NetApp Cloud-Team.
* Um das Angebot anzunehmen, sind die folgenden Google Cloud-Berechtigungen erforderlich:
+
** `roles/billing.admin`für das gewünschte Cloud-Rechnungskonto oder die Google Cloud-Organisation
** `roles/viewer`für das Projekt, das über das Cloud Billing-Konto abgerechnet wird






== Akzeptieren Sie das private Angebot in Google Cloud

Ein Google Cloud-Projekt kann nur mit einem Marketplace-Abonnement verknüpft werden. Wenn Sie zwei verschiedene Abonnements für Workloads im selben Google Cloud-Projekt verwenden möchten, müssen Sie zwei separate Konsolenkonten erstellen – eines für jedes Abonnement.

[IMPORTANT]
====
Sie müssen alle Schritte abschließen, um Ihr privates Angebot zu aktivieren. Das Überspringen von Schritten kann zu Problemen wie doppeltem Laden führen.

Wenn Sie Unstimmigkeiten in den Angebotsbedingungen, Preisen oder Details feststellen oder unsicher sind, welches Angebot Sie annehmen sollen, nehmen Sie das Angebot nicht an. Wenden Sie sich zur Klärung an Ihr NetApp -Account-Team.

====
[NOTE]
====
Wenn Sie bereits über ein aktives PAYGO-Abonnement oder ein geändertes privates Angebot verfügen, müssen Sie nur die Annahmeschritte durchführen. In diesen Fällen aktualisiert der Marketplace den Plan innerhalb derselben Auflistung und behält dieselbe Abonnement-ID bei, sodass die Abonnementzuordnung in der Konsole intakt bleibt.

====
.Schritte
. Klicken Sie auf den Aktivierungslink für das private Angebot, den Sie von Ihrem NetApp -Vertriebsteam erhalten haben. Der Link sollte ungefähr wie folgt aussehen:
`https://console.cloud.google.com/marketplace/private-offers/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee`
. Sie werden zum Google Cloud Marketplace weitergeleitet, wo Sie die Angebotsdetails überprüfen können:
+
.. **Abrechnungskonto**
.. **Produkt**: NetApp Console
.. **Angebotsdetails**
.. **Preise**
+
[NOTE]
====
Überprüfen Sie die Plandetails, die Laufzeit und die Preise sorgfältig. Wenn etwas nicht stimmt, nehmen Sie das Angebot nicht an. Wenden Sie sich für eine Änderung an Ihr NetApp -Account-Team.

====


. Bestätigen Sie die Richtigkeit der Angaben, akzeptieren Sie die Bedingungen und klicken Sie auf **Akzeptieren**.
. Während der Erstellung des Abonnements wird ein Ladesymbol angezeigt.
. Wenn das Abonnement erfolgreich erstellt wurde, wird ein Popup-Fenster angezeigt: *Ihre Bestellanfrage wurde an NetApp, Inc. gesendet.*
. Klicken Sie auf **REGISTRIEREN SIE SICH BEI NETAPP, Inc.**. Sie werden zur NetApp Console weitergeleitet, um die Konfiguration Ihres Abonnements abzuschließen. Wenn das private Angebot von einer anderen Person in Ihrer Organisation angenommen wurde:
+
.. Gehen Sie im Google Cloud Marketplace zu **Bestellungen**.
.. Suchen Sie das Angebot mit dem Status **Ausstehend**.
.. Klicken Sie auf das Drei-Punkte-Menü und wählen Sie **Bei NetApp, Inc. registrieren**.


. Sie werden weitergeleitet zu `https://console.netapp.com` und zur Anmeldung aufgefordert.
. Nach der Anmeldung werden Sie weitergeleitet zu `https://console.netapp.com/licenses/overview` . Es wird ein Popup angezeigt, in dem Sie Folgendes tun müssen:
+
.. Geben Sie einen Anzeigenamen für das *SaaS Marketplace-Abonnement* ein.
.. Wählen Sie die Konsolen-**Konten** aus, die Zugriff auf das Abonnement haben sollen.
.. Optional können Sie **Vorhandenes Abonnement ersetzen** aktivieren, wenn Sie ein vorhandenes Marketplace-Abonnement in einem Konsolenkonto automatisch ersetzen möchten.
+
[NOTE]
====
*** Diese Ersatzoption ist auf ein einzelnes Konsolenkonto beschränkt.
*** Wenn Sie mehrere Konsolenkonten mit demselben Marketplace-Abonnement verknüpfen müssen, müssen Sie die zusätzlichen Konten manuell konfigurieren.


====


. Klicken Sie auf **Partner**.
. Füllen Sie das Formular aus, um das Abonnement Ihrer Console-Organisation zuzuordnen.  Klicken Sie anschließend auf **Verknüpfen**.
. Nachdem Sie das Abonnement verknüpft haben, navigieren Sie zum Tab **Abrechnungseinstellungen** und wählen Sie diesen aus.
. Prüfen Sie die Abonnementoptionen des Marktplatzes.
. Wählen Sie das Marketplace-Abonnement aus, das Sie abrechnen möchten.  Dies gilt nur, wenn es mehr als eine Option gibt.
. Wählen Sie **Änderungen speichern**.
. Wiederholen Sie diese Schritte nach Bedarf, wenn mehrere Abonnements bei verschiedenen Hyperscalern vorhanden sind.


Weitere Informationen zu Marktplatz-Abonnements und zur Abrechnung von Direktlizenzen finden Sie unterlink:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Dokumentation der Abrechnungseinstellungen"] Die
