---
sidebar: sidebar 
permalink: task-homepage.html 
keywords: license, licensing, dashboard, capacity license, capacity based license, add license, install license, bluexp, netapp console, cloud volumes ontap license, cloud volumes ontap 
summary: Verschaffen Sie sich im Übersichts-Dashboard in der Konsole einen Überblick über alle Abonnements und Lizenzen für Ihre Organisation. 
---
= Verwenden der Dashboard-Übersicht
:allow-uri-read: 




== Verwenden der Dashboard-Übersicht

[role="lead"]
Das *Overview*-Dashboard in der NetApp Console hilft Ihnen, den Status Ihrer Licenses and subscriptions zu überwachen, um sicherzustellen, dass Sie Kosten verwalten und den Service aufrechterhalten können, wenn subscriptions das Ablaufdatum oder Kapazitätsgrenzen erreichen.

Sie können spezifische Lizenz- und Abonnementinformationen zu jedem Ihrer Datendienste (einschließlich Cloud Volumes ONTAP) einsehen.

Das Licenses and subscriptions Dashboard macht Sie auf bevorstehende Kapazitätsgrenzen oder Ablaufdaten aufmerksam und fordert Sie auf, die erforderlichen Maßnahmen zu ergreifen.



=== Details zu einem bestimmten Datendienst anzeigen

Das Dashboard *Übersicht* enthält Details zu den folgenden Services:

* Cloud Volumes ONTAP
* Notfallwiederherstellung
* Ransomware-Resilienz
* Sicherung und Wiederherstellung
* Cloud-Tiering


Beispielsweise können Administratoren, die mit der Verwaltung von Cloud Volumes ONTAP -Ressourcen beauftragt sind, die aktuelle Kapazität jeder Lizenz oder jedes Abonnements anzeigen, wodurch sie eine fokussierte Ansicht der Ressourcen in ihrem Zuständigkeitsbereich erhalten.


NOTE: Obwohl Sie Lizenzen über das Dashboard aktualisieren und entfernen können, können Sie keine neue Lizenz oder kein neues Abonnement hinzufügen.

link:task-manage-data-services-licenses.html["Erfahren Sie mehr über die Verwaltung von Lizenzen"]. link:task-manage-subscriptions.html["Weitere Informationen zum Verwalten von Abonnements"].

.Schritte
. Wählen Sie im Menü der NetApp Console *Administration > Licenses and subscriptions*.
. Wählen Sie *Übersicht*.
. Wählen Sie *Anzeigen* für den jeweiligen Datendienst (einschließlich Cloud Volumes ONTAP), um Details anzuzeigen und Lizenzen und Abonnements zu verwalten.
+
Jede Kachel bietet eine grafische Übersicht über die Kapazität.  Sie können die Detailseite anzeigen, um die Zahlungsmethoden für diese Kapazität anzuzeigen und zu verwalten.

. Wählen Sie entweder die Registerkarte *Lizenzen* oder *Abonnements*.
. Filtern Sie die Tabelle, indem Sie einen Spaltenfilter und einen Wert auswählen, nach dem gefiltert werden soll.  Beispielsweise können Sie auf der Registerkarte *Abonnements* die Spalte „Typ“ nach „Jahresvertrag“ oder „Abonnement“ filtern.
. Passen Sie die in der Tabelle angezeigten Spalten an.  Sie können Spalten zur Tabelle hinzufügen oder daraus entfernen, indem Sie das Symbol *Spalte* auswählen, um anzugeben, welche Spalten Sie ein- oder ausblenden möchten.
. Erweitern Sie eine beliebige Zeile, um Details zum Inhalt des Abonnements oder der Lizenz, zur erworbenen Kapazität und zu den Bedingungen anzuzeigen.
. Verwenden Sie das Aktionsmenü, um eine bestimmte Lizenz oder ein bestimmtes Abonnement zu verwalten, z. B. um eine Lizenz zu aktualisieren oder ein Abonnement einer anderen Organisation zuzuordnen.
+
Sie können von der Seite *Übersicht* aus keine neuen Lizenzen oder Abonnements für einen bestimmten Dienst hinzufügen.  Sie können Lizenzen oder Abonnements nur über die Registerkarte *Direktlizenzen* bzw. *Marketplace-Abonnements* hinzufügen.

+
link:task-manage-data-services-licenses.html["Erfahren Sie mehr über die Verwaltung von Lizenzen."] link:task-manage-subscriptions.html["Erfahren Sie mehr über die Verwaltung von Abonnements."]





=== Beheben von Lizenz- oder Abonnementproblemen

Im Übersichts-Dashboard können Sie Lizenz- und Abonnementprobleme einsehen, die gelöst werden müssen. Zu den Problemen gehören Lizenzen und Abonnements, die ablaufen oder ihre Kapazitätsgrenze erreichen.

. Wählen Sie im Menü der NetApp Console *Administration > Licenses and subscriptions*.
. Wählen Sie *Übersicht*.
. Wählen Sie im Bereich *Requires action* die Option *Resolve*, um die anzupassenden Probleme anzuzeigen. Wird *Resolve* nicht angezeigt, sind keine Probleme vorhanden, die eine Aktion erfordern.
. Wählen Sie auf der Seite *Aktion erforderlich* entweder die Registerkarte *Lizenzen* oder die Registerkarte *Abonnements* aus.
. Verwenden Sie das Aktionsmenü, um das Problem zu beheben.
+
link:task-manage-data-services-licenses.html["Erfahren Sie mehr über die Verwaltung von Lizenzen"]. link:task-manage-subscriptions.html["Weitere Informationen zum Verwalten von Abonnements"].


